### ISSUE TITLE
Rendre plus explicite l'action de suppression d'une playlist

### ISSUE THREAD

**Issue by mathildehg** [etalab/playlists#11]
Hello,

Lorsque je souhaite supprimer un jeu de données, je ne vois pas de croix ou de corbeille qui permet de supprimer le jdd. Est ce que le bouton en bas à droite supprime la playlist ou le jdd ?

Merci :)

**Comment by taniki** [comment]
le bouton en bas à droite supprime la playlist :) pour enlever un jeu de données d'une playlist il faut double cliquer dessus.

**Comment by taniki** [comment]
## actions possibles

- "supprimer" -> "supprimer la playlist"

**Comment by taniki** [comment]
j'avais oublié mais il y a également une modale qui ralentit et empêche de supprimer une playlist par inadvertance quand on appuie sur le bouton "supprimer".
